Nullsafety support
VerbalExpressions/DartVerbalExpressions pull request #12
Opened 2021-05-12 02:26 UTC by sergioelisan

2021-05-12 06:11 UTC, Ne4istb commented
Thanks for your PR. It will be reviewed soon.

2021-05-12 16:17 UTC, Ne4istb commented on pubspec.yaml
> +author: Ne4istb <anechytailov@gmail.com>, sergiolisan <sergiolisan@gmail.com>
```suggestion
version: 0.5.0-nullsafety
author: Ne4istb <anechytailov@gmail.com>
contributors: sergiolisan <sergiolisan@gmail.com>
```

2021-05-12 16:19 UTC, Ne4istb commented on lib/src/verbal_expression.dart
> +///
```suggestion
```

2021-05-12 16:19 UTC, Ne4istb commented on lib/src/range.dart
> +///
```suggestion
```

2021-05-12 16:21 UTC, Ne4istb commented on .vscode/launch.json
> +{
please, exclude this file and .DS_Store bellow

2021-05-12 16:23 UTC, Ne4istb requested changes
Thank you for your contribution. 
Please, fix minor issues mentioned in the comments and this PR will be merged to master branch.

2021-05-12 16:24 UTC, Ne4istb commented
And please resolve merge conflict

2021-05-13 09:06 UTC, Ne4istb requested changes
Please, delete 'test/.DS_Store'

2021-05-13 12:29 UTC, sergioelisan commented
I'm sorry, those .DS_Store are a plague!

2021-05-16 08:55 UTC, merged